title: Joseph Pascual # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
âš•ï¸ From Music Marketing to Health Care Operations Analyst
ğŸ’» Excel, Tableau, SQL, Python, R
ğŸ¾ Pickleball obsessed
ğŸ“ Sacramento, CA
<a href="https://www.linkedin.com/in/josephpascual/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-X38M2NHY95 # your Google Analytics tracking ID here
