title: Joseph Pascual
logo: "/images/IMG_4582.JPG?raw=true"
description: > 
  âš•ï¸ From Music Marketing to Health Care Operations Analyst
  <br><br>
  ğŸ’» Excel, Tableau, SQL, Python, R
  <br><br>
  ğŸ¾ Pickleball obsessed
  <br><br>
  ğŸ“ Sacramento, CA
  <br><br>
  <a href="https://www.linkedin.com/in/josephpascual/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: G-X38M2NHY95
